Use i18n text instead of Gtk::Stock::SAVE for button label
GTK4で廃止される`Gtk::Stock::SAVE`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L442

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/message/messageadmin.cpp:384:30: error: 'Gtk::Stock' has not been declared
  384 |     Gtk::Button button( Gtk::Stock::SAVE );
      |                              ^~~~~
../src/skeleton/filediag.h:27:35: error: 'Gtk::Stock' has not been declared
   27 |             else add_button( Gtk::Stock::SAVE, Gtk::RESPONSE_ACCEPT );
      |                                   ^~~~~
```