Use i18n text instead of Gtk::Stock::REVERT_TO_SAVED for button label
GTK4で廃止される`Gtk::Stock::REVERT_TO_SAVED`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L441

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:26:30: error: 'Gtk::Stock' has not been declared
   26 |       m_button_default( Gtk::Stock::REVERT_TO_SAVED )
      |                              ^~~~~
```