manual: Fix build error for jekyll theme
jekyllテーマのインストール中にエラーが出たためGemfileにテーマの追加と
不必要な.mdファイルを処理しないようにファイルの除外設定を編集します。

GitHub Actionsのエラーメッセージ
```
jekyll 3.9.0 | Error:  The jekyll-theme-cayman theme could not be found.
```

ローカルでビルドしたときのエラーメッセージ
```
Generating...
Remote Theme: Using theme pages-themes/cayman
Error: could not read file /LOCAL/JDim/docs/backup_bund/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'backup_bund/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'backup_bund/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```