Use i18n text instead of Gtk::Stock::REVERT_TO_SAVED for button label (#498)
GTK4で廃止される`Gtk::Stock::REVERT_TO_SAVED`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/498 を参照してください。

コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:26:30: error: 'Gtk::Stock' has not been declared
   26 |       m_button_default( Gtk::Stock::REVERT_TO_SAVED )
      |                              ^~~~~
```