Use Gtk::Scrollbar instead of Gtk::VScrollbar
GTK4で削除される`Gtk::VScrollbar`のかわりに`Gtk::Scrollbar`を使います。

非推奨のシンボルを無効化するマクロ
```
-DGDK_DISABLE_DEPRECATED
-DGTK_DISABLE_DEPRECATED
-DGDKMM_DISABLE_DEPRECATED
-DGTKMM_DISABLE_DEPRECATED
-DGIOMM_DISABLE_DEPRECATED
-DGLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/drawareabase.h:111:14: error: 'VScrollbar' in namespace 'Gtk' does not name a type
  111 |         Gtk::VScrollbar* m_vscrbar{};
      |              ^~~~~~~~~~
../src/article/drawareabase.h:392:14: error: 'VScrollbar' in namespace 'Gtk' does not name a type
  392 |         Gtk::VScrollbar* get_vscrbar(){ return m_vscrbar; }
      |              ^~~~~~~~~~
```