Use Gdk::Window::get_device_position() instead of Gtk::Widget::get_pointer() (#574)
GTK4で廃止される`Gtk::Widget::get_pointer()`[*]のかわりに
`Gdk::Window::get_device_position()`を使います。

参考
https://stackoverflow.com/questions/24844489/how-to-use-gdk-device-get-position

コンパイラのレポート (非推奨のシンボルを無効化)
```
../src/article/articleviewbase.cpp:1012:9: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
 1012 |         get_pointer( x, y );
      |         ^~~~~~~~~~~
      |         gpointer
../src/article/articleviewbase.cpp:1014:22: error: 'class SKELETON::PopupWin' has no member named 'get_pointer'
 1014 |         m_popup_win->get_pointer( x, y );
      |                      ^~~~~~~~~~~
../src/article/drawareabase.cpp:3188:20: error: 'class Gtk::DrawingArea' has no member named 'get_pointer'
 3188 |             m_view.get_pointer( x_point, y_point );
      |                    ^~~~~~~~~~~
../src/skeleton/edittreeview.cpp:234:17: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
  234 |                 get_pointer( x, y );
      |                 ^~~~~~~~~~~
      |                 gpointer
../src/skeleton/tabnote.cpp:168:5: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
  168 |     get_pointer( x, y );
      |     ^~~~~~~~~~~
      |     gpointer
../src/skeleton/treeviewbase.cpp:82:5: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
   82 |     get_pointer( x, y );
      |     ^~~~~~~~~~~
      |     gpointer
../src/skeleton/treeviewbase.cpp:99:5: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
   99 |     get_pointer( x, y );
      |     ^~~~~~~~~~~
      |     gpointer
../src/skeleton/view.cpp:175:5: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
  175 |     get_pointer( x, y );
      |     ^~~~~~~~~~~
      |     gpointer
```

[*]: https://developer.gnome.org/gtkmm/3.24/classGtk_1_1Widget.html#a9f27636d0f3d3be136e890ac198c50c2