setupwizard: Use Gtk::Grid instead of Gtk::Table
GTK4で廃止される`Gtk::Table`のかわりに`Gtk::Grid`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/setupwizard.h:73:14: error: 'Table' in namespace 'Gtk' does not name a type
   73 |         Gtk::Table m_table;
      |              ^~~~~
```