Use i18n text instead of Gtk::Stock::OPEN for button label (#496)
GTK4で廃止される`Gtk::Stock::OPEN`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/496 を参照してください。

コンパイラのレポート
```
../src/skeleton/filediag.h:26:78: error: 'Gtk::Stock' has not been declared
   26 |             if( m_action == Gtk::FILE_CHOOSER_ACTION_OPEN ) add_button( Gtk::Stock::OPEN, Gtk::RESPONSE_ACCEPT );
      |                                                                              ^~~~~
../src/skeleton/prefdiag.cpp:30:47: error: 'Gtk::Stock' has not been declared
   30 |     if( add_open ) m_bt_ok = add_button( Gtk::Stock::OPEN, Gtk::RESPONSE_OK );
      |                                               ^~~~~
```