PopupWin: Use Gdk::Seat instead of Gdk::DeviceManager (#573)
GTK4で廃止される`Gdk::DeviceManager`[*]のかわりに`Gdk::Seat`を使います。

コンパイラのレポート (非推奨のシンボルを無効化)
```
../src/skeleton/popupwin.cpp:51:34: error: 'class Gdk::Display' has no member named 'get_device_manager'
   51 |     Gdk::Display::get_default()->get_device_manager()->get_client_pointer()->get_position( x_mouse, y_mouse );
      |                                  ^~~~~~~~~~~~~~~~~~
```

[*]: https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-device-manager