Use Gtk::Menu::popup_at_poitner() instead of popup()
GTK3.22から廃止予定になった`Gtk::Menu::popup()`のかわりに
`popup_at_poitner()`を使います。この修正でメニューを表示したときに
出る警告も表示されなくなります。

非推奨シンボルを無効化したときのコンパイルエラー
```
../src/history/historysubmenu.cpp:213:21: error: 'class Gtk::Menu' has no member named 'popup'
  213 |         m_popupmenu.popup( 0, gtk_get_current_event_time() );
      |                     ^~~~~
../src/skeleton/admin.cpp:2211:20: error: 'class Gtk::Menu' has no member named 'popup'
 2211 |         popupmenu->popup( 0, gtk_get_current_event_time() );
      |                    ^~~~~
../src/usrcmdpref.cpp:271:11: error: 'class Gtk::Menu' has no member named 'popup'
  271 |     menu->popup( 0, gtk_get_current_event_time() );
      |           ^~~~~
```

実行時にメニュー表示したときの警告
```
Gdk-Message: 14:27:42.082: Window 0x55f2df8abd40 is a temporary window without parent, application will not be able to position it on screen.

(jdim:120146): Gdk-CRITICAL **: 14:27:42.091: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```