Remove unused MsgDiag::add_default_button(const Gtk::StockID&, const int) (#508)
GTK4で廃止される`Gtk::StockID`を使う関数オーバーロードを削除します。

コンパイラのレポート
```
../src/skeleton/msgdiag.cpp:52:66: error: no matching function for call to 'Gtk::Button::Button(const Gtk::StockID&)'
   52 |     Gtk::Button* button = Gtk::manage( new Gtk::Button( stock_id ) );
      |                                                                  ^
```