Use Gtk::GestureMultiPress instead of Gtk::Button::signal_pressed/released (#453)
GTK4で廃止される`Gtk::Button`の`pressed/released`シグナルハンドラの
かわりに`Gtk::GestureMultiPress`を使います。

非推奨のシンボルを無効化するマクロ
```
-DGDK_DISABLE_DEPRECATED
-DGTK_DISABLE_DEPRECATED
-DGDKMM_DISABLE_DEPRECATED
-DGTKMM_DISABLE_DEPRECATED
-DGIOMM_DISABLE_DEPRECATED
-DGLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/image/imageadmin.cpp:62:12: error: 'class Gtk::Button' has no member named 'signal_pressed'; did you mean 'on_pressed'?
   62 |     m_left.signal_pressed().connect( sigc::mem_fun( *this, &ImageAdmin::slot_press_left ) );
      |            ^~~~~~~~~~~~~~
      |            on_pressed
../src/image/imageadmin.cpp:63:13: error: 'class Gtk::Button' has no member named 'signal_pressed'; did you mean 'on_pressed'?
   63 |     m_right.signal_pressed().connect( sigc::mem_fun( *this, &ImageAdmin::slot_press_right ) );
      |             ^~~~~~~~~~~~~~
      |             on_pressed
../src/image/imageadmin.cpp:64:12: error: 'class Gtk::Button' has no member named 'signal_released'; did you mean 'on_released'?
   64 |     m_left.signal_released().connect( sigc::mem_fun( *this, &ImageAdmin::slot_release_left ) );
      |            ^~~~~~~~~~~~~~~
      |            on_released
../src/image/imageadmin.cpp:65:13: error: 'class Gtk::Button' has no member named 'signal_released'; did you mean 'on_released'?
   65 |     m_right.signal_released().connect( sigc::mem_fun( *this, &ImageAdmin::slot_release_right ) );
      |             ^~~~~~~~~~~~~~~
      |             on_released
```