Use Gdk::RGBA instead of Gdk::Color
GTK4で削除される`Gtk::Color`のかわりに`Gtk::RGBA`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/bbslist/columns.cpp:26:107: error: invalid use of incomplete type 'class Gdk::Color'
   26 |     if( type == TYPE_COMMENT ) row[ m_fgcolor ] = Gdk::Color( CONFIG::get_color( COLOR_CHAR_BBS_COMMENT ) );
      |                                                                                                           ^
../src/bbslist/bbslistviewbase.cpp:617:121: error: invalid use of incomplete type 'class Gdk::Color'
  617 |         if( type == TYPE_COMMENT ) row[ m_columns.m_fgcolor ] = Gdk::Color( CONFIG::get_color( COLOR_CHAR_BBS_COMMENT ) );
      |                                                                                                                         ^
../src/image/imageareaicon.cpp:170:104: error: invalid use of incomplete type 'class Gdk::Color'
  170 |         m_pixbuf_loading->fill( MISC::color_to_int( Gdk::Color( CONFIG::get_color( COLOR_IMG_LOADING ) ) ) );
      |                                                                                                        ^
../src/image/imageareaicon.cpp:171:96: error: invalid use of incomplete type 'class Gdk::Color'
  171 |         m_pixbuf_err->fill( MISC::color_to_int( Gdk::Color( CONFIG::get_color( COLOR_IMG_ERR ) ) ) );
      |                                                                                                ^
../src/jdlib/miscgtk.cpp:21:16: error: invalid use of incomplete type 'const class Gdk::Color'
   21 |     l_rgb[0] = color.get_red();
      |                ^~~~~
../src/jdlib/miscgtk.cpp:22:16: error: invalid use of incomplete type 'const class Gdk::Color'
   22 |     l_rgb[1] = color.get_green();
      |                ^~~~~
../src/jdlib/miscgtk.cpp:23:16: error: invalid use of incomplete type 'const class Gdk::Color'
   23 |     l_rgb[2] = color.get_blue();
      |                ^~~~~
../src/jdlib/miscgtk.cpp:102:19: error: invalid use of incomplete type 'const class Gdk::Color'
  102 |     guint32 red = color.get_red() >> 8;
      |                   ^~~~~
../src/jdlib/miscgtk.cpp:103:21: error: invalid use of incomplete type 'const class Gdk::Color'
  103 |     guint32 green = color.get_green() >> 8;
      |                     ^~~~~
../src/jdlib/miscgtk.cpp:104:20: error: invalid use of incomplete type 'const class Gdk::Color'
  104 |     guint32 blue = color.get_blue() >> 8;
      |                    ^~~~~
../src/core.cpp:1679:31: error: variable 'Gdk::Color color' has initializer but incomplete type
 1679 |     Gdk::Color color( CONFIG::get_color( id ) );
      |                               ^~~~~~~~~
../src/fontcolorpref.cpp:457:74: error: invalid use of incomplete type 'class Gdk::Color'
  457 |         sel->set_current_color( Gdk::Color( CONFIG::get_color( colorid ) ) );
      |                                                                          ^
../src/fontcolorpref.cpp:457:74: error: invalid use of incomplete type 'class Gdk::Color'
  457 |         sel->set_current_color( Gdk::Color( CONFIG::get_color( colorid ) ) );
      |                                                                          ^
../src/core.cpp:1679:31: error: variable 'Gdk::Color color' has initializer but incomplete type
 1679 |     Gdk::Color color( CONFIG::get_color( id ) );
      |                               ^~~~~~~~~
```