Remove unused MsgDiag::add_default_button(const Gtk::StockID&, const int)
GTK4で廃止される`Gtk::StockID`を使う関数オーバーロードを削除します。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/msgdiag.cpp:52:66: error: no matching function for call to 'Gtk::Button::Button(const Gtk::StockID&)'
   52 |     Gtk::Button* button = Gtk::manage( new Gtk::Button( stock_id ) );
      |                                                                  ^
```