PopupWin: Use Gdk::Seat instead of Gdk::DeviceManager
GTK4で廃止される`Gdk::DeviceManager`[*]のかわりに`Gdk::Seat`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/popupwin.cpp:51:34: error: 'class Gdk::Display' has no member named 'get_device_manager'
   51 |     Gdk::Display::get_default()->get_device_manager()->get_client_pointer()->get_position( x_mouse, y_mouse );
      |                                  ^~~~~~~~~~~~~~~~~~
```

[*]: https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-device-manager