Use i18n text instead of Gtk::Stock::(ADD|DELETE) for button label
GTK4で廃止される`Gtk::Stock::(ADD|DELETE)`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献:
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L346

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/control/mousekeypref.cpp:272:29: error: 'Gtk::Stock' has not been declared
  272 |       m_button_delete( Gtk::Stock::DELETE ),
      |                             ^~~~~
../src/control/mousekeypref.cpp:273:26: error: 'Gtk::Stock' has not been declared
  273 |       m_button_add( Gtk::Stock::ADD ),
      |                          ^~~~~
../src/linkfilterpref.cpp:70:29: error: 'Gtk::Stock' has not been declared
   70 |       m_button_delete( Gtk::Stock::DELETE ),
      |                             ^~~~~
../src/linkfilterpref.cpp:71:26: error: 'Gtk::Stock' has not been declared
   71 |       m_button_add( Gtk::Stock::ADD )
      |                          ^~~~~
```