Use i18n text instead of Gtk::Stock::SAVE for button label (#497)
GTK4で廃止される`Gtk::Stock::SAVE`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/497 を参照してください。

コンパイラのレポート
```
../src/message/messageadmin.cpp:384:30: error: 'Gtk::Stock' has not been declared
  384 |     Gtk::Button button( Gtk::Stock::SAVE );
      |                              ^~~~~
../src/skeleton/filediag.h:27:35: error: 'Gtk::Stock' has not been declared
   27 |             else add_button( Gtk::Stock::SAVE, Gtk::RESPONSE_ACCEPT );
      |                                   ^~~~~
```