Use i18n text and nemed icon instead of Gtk::Stock for buttons
GTK4で廃止される`Gtk::Stock`をi18n対応テキストとアイコンテーマに
置き換えます。ナビゲージョンのアイコンは表示したほうが分かりやすいと
判断したため残しておきます。

Gtk::Stockからラベルに変更する参考文献
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/linkfilterpref.cpp:66:26: error: 'Gtk::Stock' has not been declared
   66 |       m_button_top( Gtk::Stock::GOTO_TOP ),
      |                          ^~~~~
../src/linkfilterpref.cpp:67:25: error: 'Gtk::Stock' has not been declared
   67 |       m_button_up( Gtk::Stock::GO_UP ),
      |                         ^~~~~
../src/linkfilterpref.cpp:68:27: error: 'Gtk::Stock' has not been declared
   68 |       m_button_down( Gtk::Stock::GO_DOWN ),
      |                           ^~~~~
../src/linkfilterpref.cpp:69:29: error: 'Gtk::Stock' has not been declared
   69 |       m_button_bottom( Gtk::Stock::GOTO_BOTTOM ),
      |                             ^~~~~
../src/skeleton/selectitempref.cpp:20:26: error: 'Gtk::Stock' has not been declared
   20 |       m_button_top( Gtk::Stock::GOTO_TOP ),
      |                          ^~~~~
../src/skeleton/selectitempref.cpp:21:25: error: 'Gtk::Stock' has not been declared
   21 |       m_button_up( Gtk::Stock::GO_UP ),
      |                         ^~~~~
../src/skeleton/selectitempref.cpp:22:27: error: 'Gtk::Stock' has not been declared
   22 |       m_button_down( Gtk::Stock::GO_DOWN ),
      |                           ^~~~~
../src/skeleton/selectitempref.cpp:23:29: error: 'Gtk::Stock' has not been declared
   23 |       m_button_bottom( Gtk::Stock::GOTO_BOTTOM ),
      |                             ^~~~~
```