Use i18n text instead of Gtk::Stock::YES for button label
GTK4で廃止される`Gtk::Stock::YES`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献:
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/articleviewbase.cpp:1127:44: error: 'Gtk::Stock' has not been declared
 1127 |             mdiag.add_default_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                            ^~~~~
../src/bbslist/bbslistviewbase.cpp:2632:48: error: 'Gtk::Stock' has not been declared
 2632 |                         mdiag.add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                                ^~~~~
../src/cache.cpp:1075:32: error: 'Gtk::Stock' has not been declared
 1075 |         mdiag.add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                ^~~~~
../src/dbtree/articlebase.cpp:1663:44: error: 'Gtk::Stock' has not been declared
 1663 |                     mdiag.add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                            ^~~~~
../src/dbtree/boardbase.cpp:1653:32: error: 'Gtk::Stock' has not been declared
 1653 |         mdiag.add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                ^~~~~
../src/message/messageview.cpp:108:32: error: 'Gtk::Stock' has not been declared
  108 |         mdiag.add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                                ^~~~~
../src/skeleton/msgdiag.cpp:178:30: error: 'Gtk::Stock' has not been declared
  178 |             add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                              ^~~~~
../src/skeleton/msgdiag.cpp:184:57: error: 'Gtk::Stock' has not been declared
  184 |             button = Gtk::manage( new Gtk::Button( Gtk::Stock::YES ) );
      |                                                         ^~~~~
../src/skeleton/msgdiag.cpp:205:22: error: 'Gtk::Stock' has not been declared
  205 |     add_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
      |                      ^~~~~
```