Use i18n text instead of Gtk::Stock::APPLY for button label (#492)
GTK4で廃止される`Gtk::Stock::APPLY`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/492 を参照してください。

コンパイラのレポート
```
../src/skeleton/prefdiag.cpp:17:73: error: 'Gtk::Stock' has not been declared
   17 |     : Gtk::Dialog(), m_url( url ), m_bt_ok( nullptr ), m_bt_apply( Gtk::Stock::APPLY )
      |                                                                         ^~~~~
```