Fix build error for meson 0.57 (#614)
Since Meson 0.57, `test` subcommand will only rebuild test program [1]
In JDim, this causes build error because generating rule of the test
program does not include `buildinfo.h`. Therefore, fix the rule to
include the header file.

Fix GitHub Actions CI settings to build the executable file explicitly.

Error message
```
In file included from ../src/environment.cpp:10:
../src/jdversion.h:10:10: fatal error: buildinfo.h: No such file or directory
   10 | #include "buildinfo.h"
      |          ^~~~~~~~~~~~~
```

[1]: https://mesonbuild.com/Release-notes-for-0-57-0.html#meson-test-only-rebuilds-test-dependencies