Use i18n text instead of Gtk::Stock::(ADD|DELETE) for button label (#495)
GTK4で廃止される`Gtk::Stock::(ADD|DELETE)`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/495 を参照してください。

コンパイラのレポート
```
../src/control/mousekeypref.cpp:272:29: error: 'Gtk::Stock' has not been declared
  272 |       m_button_delete( Gtk::Stock::DELETE ),
      |                             ^~~~~
../src/control/mousekeypref.cpp:273:26: error: 'Gtk::Stock' has not been declared
  273 |       m_button_add( Gtk::Stock::ADD ),
      |                          ^~~~~
../src/linkfilterpref.cpp:70:29: error: 'Gtk::Stock' has not been declared
   70 |       m_button_delete( Gtk::Stock::DELETE ),
      |                             ^~~~~
../src/linkfilterpref.cpp:71:26: error: 'Gtk::Stock' has not been declared
   71 |       m_button_add( Gtk::Stock::ADD )
      |                          ^~~~~
```