Use Gtk::Dialog::get_content_area() instead of get_vbox() part1
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに
`Gtk::Dialog::get_content_area()`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/preference.cpp:203:5: error: 'get_vbox' was not declared in this scope
  203 |     get_vbox()->pack_start( m_notebook );
      |     ^~~~~~~~
../src/bbslist/addetcdialog.cpp:35:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   35 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
      |     m_vbox
../src/bbslist/selectdialog.cpp:88:5: error: 'get_vbox' was not declared in this scope
   88 |     get_vbox()->pack_start( m_label_name, Gtk::PACK_SHRINK );
      |     ^~~~~~~~
../src/bbslist/selectdialog.cpp:149:13: error: 'get_vbox' was not declared in this scope
  149 |             get_vbox()->pack_start(* m_selectview );
      |             ^~~~~~~~
../src/bbslist/selectdialog.cpp:157:9: error: 'get_vbox' was not declared in this scope
  157 |         get_vbox()->remove( *m_selectview );
      |         ^~~~~~~~
../src/board/preference.cpp:360:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
  360 |     get_vbox()->pack_start( m_notebook );
      |     ^~~~~~~~
      |     m_vbox
../src/browserpref.h:70:13: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   70 |             get_vbox()->set_spacing( 0 );
      |             ^~~~~~~~
      |             m_vbox
../src/config/aboutconfig.cpp:73:5: error: 'get_vbox' was not declared in this scope
   73 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/config/aboutconfigdiag.cpp:22:5: error: 'get_vbox' was not declared in this scope
   22 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/config/aboutconfigdiag.cpp:59:5: error: 'get_vbox' was not declared in this scope
   59 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/config/aboutconfigdiag.cpp:101:5: error: 'get_vbox' was not declared in this scope
  101 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
```