Use Gtk::Dialog::get_content_area() instead of get_vbox() part3
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに
`Gtk::Dialog::get_content_area()`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/privacypref.h:74:13: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   74 |             get_vbox()->set_spacing( 8 );
      |             ^~~~~~~~
      |             m_vbox
../src/proxypref.h:139:13: error: 'get_vbox' was not declared in this scope
  139 |             get_vbox()->set_spacing( 4 );
      |             ^~~~~~~~
../src/setupwizard.cpp:297:5: error: 'get_vbox' was not declared in this scope
  297 |     get_vbox()->pack_start( m_notebook, Gtk::PACK_EXPAND_PADDING, SPACING_SIZE );
      |     ^~~~~~~~
../src/skeleton/aboutdiag.cpp:133:5: error: 'get_vbox' was not declared in this scope
  133 |     get_vbox()->pack_start( m_notebook, Gtk::PACK_EXPAND_WIDGET, MARGIN );
      |     ^~~~~~~~
../src/skeleton/detaildiag.cpp:35:5: error: 'get_vbox' was not declared in this scope
   35 |     get_vbox()->pack_start( m_notebook );
      |     ^~~~~~~~
../src/skeleton/editviewdialog.h:25:13: error: 'get_vbox' was not declared in this scope
   25 |             get_vbox()->pack_start( m_edit  );
      |             ^~~~~~~~
../src/skeleton/msgdiag.cpp:156:5: error: 'get_vbox' was not declared in this scope
  156 |     get_vbox()->pack_start( *hbox, Gtk::PACK_SHRINK );
      |     ^~~~~~~~
../src/skeleton/selectitempref.cpp:127:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
  127 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
      |     m_vbox
../src/usrcmdmanager.cpp:61:9: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   61 |         get_vbox()->set_spacing( 8 );
      |         ^~~~~~~~
      |         m_vbox
../src/usrcmdpref.cpp:49:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   49 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
      |     m_vbox
../src/usrcmdpref.cpp:90:5: error: 'get_vbox' was not declared in this scope
   90 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
```