meson: Improve JDim build configuration and fix library conflict issue
Meson の構成を更新し、JDim のコア部分(src/ にあるソースファイル)を
静的ライブラリにまとめました。
この静的ライブラリを、JDim の実行ファイルとテストプログラムに
リンクさせます。 この変更前は、2つのビルドターゲットに対して
ソースファイルを別々にコンパイルし、リンクしていました。

また、Meson の Unity build の block size を大きくすると、
X11 ライブラリのヘッダーファイルで定義されたマクロ(Bool, None)が
Google Test の識別子と競合し、コンパイルエラーが発生する問題がありました。
この修正によって、2つのライブラリを同時に使用する箇所が無くなるため、
この問題は解消されます。

gccのコンパイルエラー
```
/usr/include/gtest/internal/gtest-type-util.h:138:8: error: expected identifier before numeric constant
  138 | struct None {};
      |        ^~~~
/usr/include/gtest/gtest-param-test.h:359:44: error: expected unqualified-id before ‘)’ token
  359 | inline internal::ParamGenerator<bool> Bool() { return Values(false, true); }
      |                                            ^
```

最後に、src/jdlib のビルド構成に欠けていた zlib_dep を追加しました。
Linux 環境では、zlib_dep が無くてもビルドは可能でしたが、
他の環境では依存関係が必要になります。

The Meson configuration has been updated to group the core part of
JDim (source files in the src/ directory) into a static library.
This static library is linked to both the JDim executable and the
test program. Before this change, the source files were compiled and
linked separately for the two build targets.

Additionally, increasing the block size of Meson's Unity build caused
a compile error due to conflicts between macros (Bool, None) defined
in the X11 library headers and identifiers in Google Test. This issue
is resolved by this fix, as the parts where both libraries are used
together are eliminated.

Lastly, zlib_dep, which was missing from the build configuration of
src/jdlib, has been added. While zlib_dep wasn't required for
building in Linux environments, it is necessary for other environments.