Use i18n text instead of Gtk::Stock::NO for button label
GTK4で廃止される`Gtk::Stock::NO`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献:
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/articleviewbase.cpp:1126:36: error: 'Gtk::Stock' has not been declared
 1126 |             mdiag.add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                                    ^~~~~
../src/bbslist/bbslistviewbase.cpp:2631:56: error: 'Gtk::Stock' has not been declared
 2631 |                         mdiag.add_default_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                                                        ^~~~~
../src/cache.cpp:1074:32: error: 'Gtk::Stock' has not been declared
 1074 |         mdiag.add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                                ^~~~~
../src/dbtree/articlebase.cpp:1664:46: error: 'Gtk::Stock' has not been declared
 1664 |                     Gtk::Button button( Gtk::Stock::NO );
      |                                              ^~~~~
../src/dbtree/boardbase.cpp:1652:40: error: 'Gtk::Stock' has not been declared
 1652 |         mdiag.add_default_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                                        ^~~~~
../src/message/messageview.cpp:107:32: error: 'Gtk::Stock' has not been declared
  107 |         mdiag.add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                                ^~~~~
../src/skeleton/msgdiag.cpp:166:26: error: 'Gtk::Stock' has not been declared
  166 |         add_button( Gtk::Stock::NO, Gtk::RESPONSE_CANCEL );
      |                          ^~~~~
../src/skeleton/msgdiag.cpp:175:57: error: 'Gtk::Stock' has not been declared
  175 |             button = Gtk::manage( new Gtk::Button( Gtk::Stock::NO ) );
      |                                                         ^~~~~
../src/skeleton/msgdiag.cpp:182:30: error: 'Gtk::Stock' has not been declared
  182 |             add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                              ^~~~~
../src/skeleton/msgdiag.cpp:204:22: error: 'Gtk::Stock' has not been declared
  204 |     add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
      |                      ^~~~~
```