Use Gtk::Menu::popup_at_widget() instead of popup()
GTK3.22から廃止予定になった`Gtk::Menu::popup()`のかわりに
`popup_at_widget()`を使います。この修正でメニューを表示したときに
出る警告も表示されなくなります。

非推奨シンボルを無効化したときのコンパイルエラー
```
../src/skeleton/admin.cpp:2231:22: error: 'class SKELETON::TabSwitchMenu' has no member named 'popup'
 2231 |     m_tabswitchmenu->popup( Gtk::Menu::SlotPositionCalc( sigc::mem_fun( *this, &Admin::slot_popup_pos ) ),
      |                      ^~~~~
../src/skeleton/admin.cpp:2231:40: error: 'SlotPositionCalc' is not a member of 'Gtk::Menu'
 2231 |     m_tabswitchmenu->popup( Gtk::Menu::SlotPositionCalc( sigc::mem_fun( *this, &Admin::slot_popup_pos ) ),
      |                                        ^~~~~~~~~~~~~~~~
../src/skeleton/menubutton.cpp:130:18: error: 'class Gtk::Menu' has no member named 'popup'
  130 |     m_popupmenu->popup( Gtk::Menu::SlotPositionCalc( sigc::mem_fun( *this, &MenuButton::slot_popup_pos ) ),
      |                  ^~~~~
../src/skeleton/menubutton.cpp:130:36: error: 'SlotPositionCalc' is not a member of 'Gtk::Menu'
  130 |     m_popupmenu->popup( Gtk::Menu::SlotPositionCalc( sigc::mem_fun( *this, &MenuButton::slot_popup_pos ) ),
      |                                    ^~~~~~~~~~~~~~~~
```

実行時にメニュー表示したときの警告
```
Gdk-Message: 14:27:42.082: Window 0x55f2df8abd40 is a temporary window without parent, application will not be able to position it on screen.

(jdim:120146): Gdk-CRITICAL **: 14:27:42.091: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```