Use Gtk::Dialog::get_content_area() instead of get_vbox() part4 (#546)
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに
`Gtk::Dialog::get_content_area()`を使います。

コンパイラのレポート
```
../src/replacestrpref.cpp:68:5: error: ‘get_vbox’ was not declared in this scope
   68 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/replacestrpref.cpp:211:5: error: ‘get_vbox’ was not declared in this scope
  211 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
```