Use Gtk::Label::set_xalign() instead of Gtk::Misc::set_alignment()
GTK4で廃止される`Gtk::Misc::set_alignment()`のかわりに
`Gtk::Label::set_xalign()`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/preference.cpp:124:23: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
  124 |         m_label_abone.set_alignment( Gtk::ALIGN_START, Gtk::ALIGN_CENTER );
      |                       ^~~~~~~~~~~~~
      |                       set_lines
../src/bbslist/toolbar.cpp:38:13: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
   38 |     m_label.set_alignment( Gtk::ALIGN_START );
      |             ^~~~~~~~~~~~~
      |             set_lines
../src/message/messageviewbase.cpp:429:18: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
  429 |     m_label_name.set_alignment( Gtk::ALIGN_START, Gtk::ALIGN_CENTER );
      |                  ^~~~~~~~~~~~~
      |                  set_lines
../src/message/messageviewbase.cpp:430:18: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
  430 |     m_label_mail.set_alignment( Gtk::ALIGN_START, Gtk::ALIGN_CENTER );
      |                  ^~~~~~~~~~~~~
      |                  set_lines
../src/skeleton/label_entry.cpp:21:12: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
   21 |     m_info.set_alignment( Gtk::ALIGN_START );
      |            ^~~~~~~~~~~~~
      |            set_lines
../src/skeleton/toolbar.cpp:303:18: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
  303 |         m_label->set_alignment( Gtk::ALIGN_START );
      |                  ^~~~~~~~~~~~~
      |                  set_lines
../src/skeleton/toolbar.cpp:633:24: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
  633 |         m_label_board->set_alignment( Gtk::ALIGN_START );
      |                        ^~~~~~~~~~~~~
      |                        set_lines
../src/skeleton/window.cpp:61:18: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
   61 |     m_label_stat.set_alignment( Gtk::ALIGN_START );
      |                  ^~~~~~~~~~~~~
      |                  set_lines
../src/skeleton/window.cpp:77:14: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
   77 |     m_mginfo.set_alignment( Gtk::ALIGN_START );
      |              ^~~~~~~~~~~~~
      |              set_lines
../src/browserpref.h:63:28: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
   63 |             m_label_notice.set_alignment( Gtk::ALIGN_START, Gtk::ALIGN_CENTER );
      |                            ^~~~~~~~~~~~~
      |                            set_lines
```