Revert "Implement PrefDiag::set_default_size_ratio()"
This reverts commit c6d57f203e79dd8c7e65f94f4a3233c4b7f1a760.
GTK4で廃止される`Gdk::Screen::get_width/height()`を利用する関数を削除します。

コンパイラのレポート (非推奨のシンボルを無効化)
```
../src/skeleton/prefdiag.cpp:103:51: error: 'class Gdk::Screen' has no member named 'get_width'
103 |     const int width = static_cast< int >( screen->get_width() * ratio );
  |                                                   ^~~~~~~~~
../src/skeleton/prefdiag.cpp:104:52: error: 'class Gdk::Screen' has no member named 'get_height'
104 |     const int height = static_cast< int >( screen->get_height() * ratio );
  |                                                    ^~~~~~~~~~
```