Use icon theme instead of Gtk::Arrow
GTK4で廃止される`Gtk::Arrow`のかわりにアイコンテーマを使います。

GtkArrowのリファレンス[*]より
> GtkArrow has been deprecated; you can simply use a GtkImage with
> a suitable icon name, such as "pan-down-symbolic".

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/tabswitchbutton.h:20:14: error: 'Arrow' in namespace 'Gtk' does not name a type
   20 |         Gtk::Arrow m_arrow{ Gtk::ARROW_DOWN, Gtk::SHADOW_NONE };
      |              ^~~~~
../src/skeleton/menubutton.h:28:14: error: 'Arrow' in namespace 'Gtk' does not name a type
   28 |         Gtk::Arrow* m_arrow;
      |              ^~~~~
```

[*]: https://developer.gnome.org/gtk3/stable/GtkArrow.html