Use named icons instead of Gtk::Stock::GO_(FORWARD|BACK) for button
GTK4で廃止される`Gtk::Stock::GO_(FORWARD|BACK)`をアイコンテーマに置き換えます。

Gtk::Stockからラベルに変更する参考文献
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:24:29: error: 'Gtk::Stock' has not been declared
   24 |       m_button_delete( Gtk::Stock::GO_FORWARD, std::string(), Gtk::ICON_SIZE_BUTTON ),
      |                             ^~~~~
../src/skeleton/selectitempref.cpp:25:26: error: 'Gtk::Stock' has not been declared
   25 |       m_button_add( Gtk::Stock::GO_BACK, std::string(), Gtk::ICON_SIZE_BUTTON ),
      |                          ^~~~~
```