Root: Use std::unique_ptr instead of raw pointer (#664)
クラスのメンバーをスマートポインターに更新してnew/deleteによる
メモリ割り当てを整理します。

gcc-6のエラーを回避するためオブジェクトに依存しない
メンバー関数をstaticに変更します。

gcc-6のエラーログ
```
../src/dbtree/root.cpp:209:48: error: cannot call member function ‘bool DBTREE::Root::is_2ch(const string&)’ without object
                 return is_2ch( b->get_root() ) && url.find( b->get_path_board() + "/" ) != std::string::npos;
```