Use i18n text instead of Gtk::Stock::CLOSE for button label (#493)
GTK4で廃止される`Gtk::Stock::CLOSE`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/493 を参照してください。

コンパイラのレポート
```
../src/skeleton/aboutdiag.cpp:31:44: error: 'Gtk::Stock' has not been declared
   31 |     Gtk::Button* button = add_button( Gtk::Stock::CLOSE, Gtk::RESPONSE_CLOSE );
      |                                            ^~~~~
```