Use i18n text instead of Gtk::Stock::OK for button label
GTK4で廃止される`Gtk::Stock::OK`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献:
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative/36811163#36811163

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/skeleton/editviewdialog.h:24:30: error: 'Gtk::Stock' has not been declared
   24 |             add_button( Gtk::Stock::OK, Gtk::RESPONSE_OK );
      |                              ^~~~~
../src/skeleton/msgdiag.cpp:162:53: error: 'Gtk::Stock' has not been declared
  162 |         button = Gtk::manage( new Gtk::Button( Gtk::Stock::OK ) );
      |                                                     ^~~~~
../src/skeleton/msgdiag.cpp:168:53: error: 'Gtk::Stock' has not been declared
  168 |         button = Gtk::manage( new Gtk::Button( Gtk::Stock::OK ) );
      |                                                     ^~~~~
../src/skeleton/prefdiag.cpp:31:37: error: 'Gtk::Stock' has not been declared
   31 |     else m_bt_ok = add_button( Gtk::Stock::OK, Gtk::RESPONSE_OK );
      |                                     ^~~~~
```