Use Gtk::Dialog::get_content_area() instead of get_vbox() part2
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに
`Gtk::Dialog::get_content_area()`を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/control/mousekeypref.cpp:41:5: error: 'get_vbox' was not declared in this scope
   41 |     get_vbox()->pack_start( m_label );
      |     ^~~~~~~~
../src/control/mousekeypref.cpp:301:5: error: 'get_vbox' was not declared in this scope
  301 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/control/mousekeypref.cpp:532:5: error: 'get_vbox' was not declared in this scope
  532 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/dbimg/delimgcachediag.cpp:34:5: error: 'get_vbox' was not declared in this scope
   34 |     get_vbox()->set_spacing( mrg );
      |     ^~~~~~~~
../src/dbimg/delimgdiag.h:110:13: error: 'get_vbox' was not declared in this scope
  110 |             get_vbox()->set_spacing( 8 );
      |             ^~~~~~~~
../src/fontcolorpref.cpp:241:5: error: 'get_vbox' was not declared in this scope
  241 |     get_vbox()->pack_start( m_notebook );
      |     ^~~~~~~~
../src/globalabonepref.h:73:13: error: 'get_vbox' was not declared in this scope
   73 |             get_vbox()->pack_start( m_notebook );
      |             ^~~~~~~~
../src/globalabonethreadpref.h:116:13: error: 'get_vbox' was not declared in this scope
  116 |             get_vbox()->pack_start( m_notebook );
      |             ^~~~~~~~
../src/image/preference.cpp:76:5: error: 'get_vbox' was not declared in this scope
   76 |     get_vbox()->pack_start( m_vbox_info );
      |     ^~~~~~~~
../src/linkfilterpref.cpp:47:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   47 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
      |     m_vbox
../src/linkfilterpref.cpp:113:5: error: 'get_vbox' was not declared in this scope
  113 |     get_vbox()->set_spacing( 8 );
      |     ^~~~~~~~
../src/livepref.cpp:66:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
   66 |     get_vbox()->set_spacing( mrg );
      |     ^~~~~~~~
      |     m_vbox
../src/main.cpp:549:20: error: 'class Gtk::MessageDialog' has no member named 'get_vbox'
  549 |             mdiag->get_vbox()->pack_start( chk_button, Gtk::PACK_SHRINK );
      |                    ^~~~~~~~
../src/message/confirmdiag.cpp:26:5: error: 'get_vbox' was not declared in this scope
   26 |     get_vbox()->pack_start( *hbox, Gtk::PACK_SHRINK );
      |     ^~~~~~~~
../src/openurldiag.cpp:18:5: error: 'get_vbox' was not declared in this scope
   18 |     get_vbox()->pack_start( m_label_url, Gtk::PACK_SHRINK );
      |     ^~~~~~~~
../src/passwdpref.h:130:13: error: 'get_vbox' was not declared in this scope
  130 |             get_vbox()->pack_start( m_notebook );
      |             ^~~~~~~~
```