Use Gtk::ColorChooserDialog instead of Gtk::ColorSelectionDialog
GTK4で廃止される`Gtk::ColorSelectionDialog`のかわりに
`Gtk::ColorChooserDialog`を使います。

JDimの関数や設定が対応してないためalphaチャンネルは無効にしてあります。

既知の問題
KDE plasma(X11?)環境では色選択ダイアログのカラーピッカーで色を抜き出す
ことができない。(関連の問題？[*])

[*]: https://bugs.kde.org/show_bug.cgi?id=407226

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/core.cpp:1681:10: error: 'ColorSelectionDialog' is not a member of 'Gtk'
 1681 |     Gtk::ColorSelectionDialog diag( title );
      |          ^~~~~~~~~~~~~~~~~~~~
../src/core.cpp:1682:5: error: 'diag' was not declared in this scope
 1682 |     diag.get_color_selection()->set_current_color( color );
      |     ^~~~
../src/core.cpp:1685:14: error: 'ColorSelection' is not a member of 'Gtk'
 1685 |         Gtk::ColorSelection* sel = diag.get_color_selection();
      |              ^~~~~~~~~~~~~~
../src/core.cpp:1685:30: error: 'sel' was not declared in this scope
 1685 |         Gtk::ColorSelection* sel = diag.get_color_selection();
      |                              ^~~
../src/fontcolorpref.cpp:454:10: error: 'ColorSelectionDialog' is not a member of 'Gtk'
  454 |     Gtk::ColorSelectionDialog colordiag;
      |          ^~~~~~~~~~~~~~~~~~~~
../src/fontcolorpref.cpp:456:14: error: 'ColorSelection' is not a member of 'Gtk'
  456 |         Gtk::ColorSelection* sel = colordiag.get_color_selection();
      |              ^~~~~~~~~~~~~~
../src/fontcolorpref.cpp:456:30: error: 'sel' was not declared in this scope
  456 |         Gtk::ColorSelection* sel = colordiag.get_color_selection();
      |                              ^~~
../src/fontcolorpref.cpp:456:36: error: 'colordiag' was not declared in this scope; did you mean 'colorid'?
  456 |         Gtk::ColorSelection* sel = colordiag.get_color_selection();
      |                                    ^~~~~~~~~
      |                                    colorid
../src/fontcolorpref.cpp:471:22: error: 'ColorSelection' is not a member of 'Gtk'
  471 |                 Gtk::ColorSelection* sel = colordiag.get_color_selection();
      |                      ^~~~~~~~~~~~~~
../src/fontcolorpref.cpp:471:38: error: 'sel' was not declared in this scope
  471 |                 Gtk::ColorSelection* sel = colordiag.get_color_selection();
      |                                      ^~~
```