Use cursor name instead of Gdk::CursorType (#449)
GTK4で削除される`Gdk::CursorType`のかわりにカーソルテーマの名前[*]を
使います。カーソル名の入力ミスを予防するため文字列リテラルを直接指定する
かわりに定数を使います。

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/article/drawareabase.cpp:5226:70: error: no matching function for call to 'Gdk::Cursor::create(Gdk::CursorType&)'
 5226 |             m_window->set_cursor( Gdk::Cursor::create( m_cursor_type ) );
      |                                                                      ^
```

[*]: https://developer.gnome.org/gdk3/stable/gdk3-Cursors.html#gdk-cursor-new-from-name