Use i18n text instead of Gtk::Stock::CANCEL for button label (#488)
GTK4で廃止される`Gtk::Stock::CANCEL`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/488 を参照してください。

コンパイラのレポート
```
../src/dbimg/delimgcachediag.cpp:28:22: error: 'Gtk::Stock' has not been declared
   28 |     add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL )
      |                      ^~~~~
../src/message/messageadmin.cpp:383:28: error: 'Gtk::Stock' has not been declared
  383 |     mdiag.add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL );
      |                            ^~~~~
../src/skeleton/admin.cpp:2724:40: error: 'Gtk::Stock' has not been declared
 2724 |                 mdiag.add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL );
      |                                        ^~~~~
../src/skeleton/filediag.h:24:30: error: 'Gtk::Stock' has not been declared
   24 |             add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL );
      |                              ^~~~~
../src/skeleton/prefdiag.cpp:26:26: error: 'Gtk::Stock' has not been declared
   26 |         add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL )
      |                          ^~~~~
```