Core: Get rid of unused private field (#1187)
未使用のprivateメンバー変数があるとclangに指摘されたため取り除きます。

clang 15のレポート
```
../src/core.h:108:24: error: private field 'm_menuitem_prevview' is not used [-Werror,-Wunused-private-field]
        Gtk::MenuItem* m_menuitem_prevview{};
                       ^
```