Use i18n text instead of Gtk::Stock::OK for button label (#487)
GTK4で廃止される`Gtk::Stock::OK`をi18n対応テキストに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/487 を参照してください。

コンパイラのレポート
```
../src/skeleton/editviewdialog.h:24:30: error: 'Gtk::Stock' has not been declared
   24 |             add_button( Gtk::Stock::OK, Gtk::RESPONSE_OK );
      |                              ^~~~~
../src/skeleton/msgdiag.cpp:162:53: error: 'Gtk::Stock' has not been declared
  162 |         button = Gtk::manage( new Gtk::Button( Gtk::Stock::OK ) );
      |                                                     ^~~~~
../src/skeleton/msgdiag.cpp:168:53: error: 'Gtk::Stock' has not been declared
  168 |         button = Gtk::manage( new Gtk::Button( Gtk::Stock::OK ) );
      |                                                     ^~~~~
../src/skeleton/prefdiag.cpp:31:37: error: 'Gtk::Stock' has not been declared
   31 |     else m_bt_ok = add_button( Gtk::Stock::OK, Gtk::RESPONSE_OK );
      |                                     ^~~~~
```