Use named icons instead of Gtk::Stock::GO_(FORWARD|BACK) for button (#500)
GTK4で廃止される`Gtk::Stock::GO_(FORWARD|BACK)`をアイコンテーマに置き換えます。

Gtk::Stockからラベルに変更する参考文献
非推奨のシンボルを無効化するマクロ
https://github.com/JDimproved/JDim/pull/500 を参照してください。

コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:24:29: error: 'Gtk::Stock' has not been declared
   24 |       m_button_delete( Gtk::Stock::GO_FORWARD, std::string(), Gtk::ICON_SIZE_BUTTON ),
      |                             ^~~~~
../src/skeleton/selectitempref.cpp:25:26: error: 'Gtk::Stock' has not been declared
   25 |       m_button_add( Gtk::Stock::GO_BACK, std::string(), Gtk::ICON_SIZE_BUTTON ),
      |                          ^~~~~
```